# Generated by Django 5.1 on 2024-08-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='music',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.news', verbose_name='Новость'),
        ),
    ]
