# Generated by Django 5.1 on 2024-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('video', models.FileField(upload_to='video/file/', verbose_name='Видео')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='video/image/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
